data:
    name: 'HPatches'
    class_name: 'HPatches'
    batch_size: 1
    alteration: 'all' # choose when running engine on Hpatches evaluation, v for viewpoint, i for illumination, all for both
    resize_side: "short"
    ignore_scenes: False
    resize: 480
    dist_thresh: 3.0
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'superpoint_prp'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        det_thresh: 0.005
        nms: 4
        iou: 0.1
        top_k: 1000
        remove_border: 4
    descriptor_head:
        descriptor_dim: [128,256]
        upsample: True
        grid_size: 8
matcher:
  cross_check: True
pretrained: ''