data:
    name: 'NeRF_dataset'
    class_name: 'NeRF'
    image_size: [480, 640]
    fov: 44
    batch_size: 32
    truncate: False
    has_labels: '' # outputs/name of the labels file
    warped_pair: False
    bound_frame_sampling: True
    augmentation:
        photometric:
            enable: True
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'magicpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: False
        det_thresh: 0.005
        top_k: False
        remove_border: False
train:
    num_iters: 25000
    learning_rate: 0.001
save_or_validation_interval: 1000
ckpt_name: '' # name of checkpoint
pretrained: '' # checkpoint_folder/checkpoint_name_iter.pth
continue_training: False