data:
    name: 'NeRF_dataset'
    class_name: 'NeRF'
    experiment_name: '' # folder name of labels/Paintings
    image_size: [480, 640]
    fov: 44
    has_labels: False
    warped_pair: False
    augmentation:
        photometric:
            enable: False
    batch_size: 20
    truncate: False
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'magicpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: 4
        det_thresh: 0.015
        top_k: False
        remove_border: False
pretrained: '' # checkpoint_folder/checkpoint_name_iter.pth