data:
    name: 'ScanNet'
    class_name: 'Scannet'
    gt_pairs: 'ScanNet/scannet_test_pairs_with_gt.txt'
    images_path:  'ScanNet'
    resize: [480, 640]
    n_thres: 0.0
    epi_thrsehold: 0.0005
    shuffle: false
    max_length: -1
    batch_size: 1
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'superpoint_prp'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        det_thresh: 0.005
        nms: 4
        iou: 0.5
        top_k: 1024
        remove_border: 4
    descriptor_head:
        descriptor_dim: [128,256]
        upsample: True
        grid_size: 4
matcher:
    ransac_thresh: 0.5
    cross_check: True
pretrained: '' # checkpoint_folder/checkpoint_name_iter.pth