data:
    name: 'YFCC'
    class_name: 'YFCC'
    gt_pairs: 'YFCC/raw_data/yfcc_test_pairs_with_gt.txt'
    images_path:  'YFCC/yfcc100m'
    resize: 1200
    n_thres: 0.0
    epi_thrsehold: 0.0001
    shuffle: false
    max_length: -1
    batch_size: 1
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'superpoint_prp'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        det_thresh: 0.005
        nms: 3
        top_k: 2048
        iou: 0.1
        remove_border: 4
    descriptor_head:
        descriptor_dim: [128,256]
        upsample: True
        grid_size: 8
matcher:
    ransac_thresh: 0.5
    cross_check: True
pretrained: '' # checkpoint_folder/checkpoint_name_iter.pth