data:
    name: 'COCO'
    class_name: 'COCO'
    has_labels: '' # outputs/name of the labels file
    preprocessing:
        resize: [240, 320] 
    batch_size: 2
    truncate: False
    warped_pair: True
    augmentation:
        photometric:
            enable: True
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: False
        pair_homography:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                n_scales: 5
                n_angles: 25
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
                translation_overflow: 0.
            valid_border_margin: 3
model:
    script: 'SuperPoint_PrP'
    class_name: 'SuperPointPrP'
    model_name: 'superpoint_prp'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: False
        det_thresh: 0.005
        top_k: False
        iou: 0.1
        remove_border: False
    descriptor_head:
        descriptor_dim: [128,256]
        upsample: False
        grid_size: 8
        desc_dist: 8
        positive_margin: 1.0
        negative_margin: 0.2
        lambda_d: 0.05
        lambda_loss: 10000
        normalise_descriptors: True
train:
    num_iters: 300000
    learning_rate: 0.0001
save_or_validation_interval: 10000
ckpt_name: '' # checkpoint name
pretrained: False
continue_training: False